In [1]:
from textblob import TextBlob

In [2]:
q = input("Please enter the text:")

Please enter the text:happ


In [3]:
print(TextBlob(q).sentiment)

Sentiment(polarity=0.0, subjectivity=0.0)


In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:/Users/MOJITO/Desktop/lecture/NTU AI/Slides/Day 4/Speech_and_Text_Notes-20230717/spam (Text) for orange.csv")

In [6]:
X = df["CONTENT"]
Y = df["SPAM"]

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
X_CV = CountVectorizer().fit_transform(X)

In [9]:
X_CV

<5572x8709 sparse matrix of type '<class 'numpy.int64'>'
	with 74098 stored elements in Compressed Sparse Row format>

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn import ensemble

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X_CV, Y)
model = LogisticRegression()
model.fit(X_train, Y_train)
pred = model.predict(X_test)
cm=confusion_matrix(Y_test, pred)
print(cm)
acc=(cm[0,0]+cm[1,1])/sum(sum(cm))
print('Accuracy without TFIDF is ', acc)

[[1211    2]
 [  27  153]]
Accuracy without TFIDF is  0.9791816223977028


In [12]:
model = ensemble.RandomForestClassifier()
model.fit(X_train, Y_train)
pred = model.predict(X_test)
cm=confusion_matrix(Y_test, pred)
print(cm)
acc=(cm[0,0]+cm[1,1])/sum(sum(cm))
print('Accuracy without TFIDF is ', acc)

[[1213    0]
 [  38  142]]
Accuracy without TFIDF is  0.9727207465900933


In [13]:
from sklearn.feature_extraction.text import TfidfTransformer

In [14]:
X_train = TfidfTransformer().fit_transform(X_train)

In [15]:
X_test = TfidfTransformer().fit_transform(X_test)

In [16]:
X_train

<4179x8709 sparse matrix of type '<class 'numpy.float64'>'
	with 55771 stored elements in Compressed Sparse Row format>

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X_CV, Y)
model = LogisticRegression()
model.fit(X_train, Y_train)
pred = model.predict(X_test)
cm=confusion_matrix(Y_test, pred)
print(cm)
acc=(cm[0,0]+cm[1,1])/sum(sum(cm))
print('Accuracy with TFIDF is ', acc)

[[1210    4]
 [  22  157]]
Accuracy with TFIDF is  0.9813352476669059


In [18]:
model = ensemble.RandomForestClassifier()
model.fit(X_train, Y_train)
pred = model.predict(X_test)
cm=confusion_matrix(Y_test, pred)
print(cm)
acc=(cm[0,0]+cm[1,1])/sum(sum(cm))
print('Accuracy with TFIDF is ', acc)

[[1212    2]
 [  26  153]]
Accuracy with TFIDF is  0.9798994974874372


In [19]:
from sentence_transformers import SentenceTransformer

In [20]:
model = SentenceTransformer('bert-base-nli-mean-tokens')

In [21]:
X_bert = model.encode(X)

In [22]:
X_bert

array([[ 0.22050568,  0.2599657 ,  1.225875  , ..., -0.19872397,
         0.5879919 , -0.07510579],
       [ 0.34306562,  0.25109184,  1.7299985 , ...,  0.12130548,
         0.34931996,  0.2205923 ],
       [-1.0374186 ,  0.7675856 ,  1.2479769 , ...,  0.04645469,
         0.44673648,  0.95130104],
       ...,
       [-0.05629906,  0.02633081,  1.8031619 , ...,  0.1250096 ,
        -0.33973387,  0.17344324],
       [-0.30574158, -0.2067655 ,  0.95200235, ...,  0.8162919 ,
        -0.06555745,  0.37663952],
       [ 0.25440854, -0.22606559,  1.7392159 , ...,  0.34476784,
        -0.21240988,  0.38669977]], dtype=float32)

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X_bert, Y)

In [24]:
model = LogisticRegression()
model.fit(X_train, Y_train)
pred = model.predict(X_test)
cm=confusion_matrix(Y_test, pred)
print(cm)
acc=(cm[0,0]+cm[1,1])/sum(sum(cm))
print('Accuracy is ', acc)

[[1225    6]
 [  11  151]]
Accuracy is  0.9877961234745154


C:\Users\MOJITO\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [25]:
model = ensemble.RandomForestClassifier()
model.fit(X_train, Y_train)
pred = model.predict(X_test)
cm=confusion_matrix(Y_test, pred)
print(cm)
acc=(cm[0,0]+cm[1,1])/sum(sum(cm))
print('Accuracy is ', acc)

[[1229    2]
 [  36  126]]
Accuracy is  0.9727207465900933
